// <auto-generated />
using Journy.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Journey.Migrations
{
    [DbContext(typeof(JourneyContext))]
    [Migration("20240508104035_UpdateUserPin2")]
    partial class UpdateUserPin2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Journy.Model.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            CountryName = "Afghanistan"
                        },
                        new
                        {
                            Id = 3,
                            CountryName = "Åland Islands"
                        },
                        new
                        {
                            Id = 4,
                            CountryName = "Albania"
                        },
                        new
                        {
                            Id = 5,
                            CountryName = "Algeria"
                        },
                        new
                        {
                            Id = 6,
                            CountryName = "American Samoa"
                        },
                        new
                        {
                            Id = 7,
                            CountryName = "Andorra"
                        },
                        new
                        {
                            Id = 8,
                            CountryName = "Angola"
                        },
                        new
                        {
                            Id = 9,
                            CountryName = "Anguilla"
                        },
                        new
                        {
                            Id = 10,
                            CountryName = "Antarctica"
                        },
                        new
                        {
                            Id = 11,
                            CountryName = "Antigua & Barbuda"
                        },
                        new
                        {
                            Id = 12,
                            CountryName = "Argentina"
                        },
                        new
                        {
                            Id = 13,
                            CountryName = "Armenia"
                        },
                        new
                        {
                            Id = 14,
                            CountryName = "Aruba"
                        },
                        new
                        {
                            Id = 15,
                            CountryName = "Australia"
                        },
                        new
                        {
                            Id = 16,
                            CountryName = "Austria"
                        },
                        new
                        {
                            Id = 17,
                            CountryName = "Azerbaijan"
                        },
                        new
                        {
                            Id = 18,
                            CountryName = "Bahamas"
                        },
                        new
                        {
                            Id = 19,
                            CountryName = "Bahrain"
                        },
                        new
                        {
                            Id = 20,
                            CountryName = "Bangladesh"
                        },
                        new
                        {
                            Id = 21,
                            CountryName = "Barbados"
                        },
                        new
                        {
                            Id = 22,
                            CountryName = "Belarus"
                        },
                        new
                        {
                            Id = 23,
                            CountryName = "Belgium"
                        },
                        new
                        {
                            Id = 24,
                            CountryName = "Belize"
                        },
                        new
                        {
                            Id = 25,
                            CountryName = "Benin"
                        },
                        new
                        {
                            Id = 26,
                            CountryName = "Bermuda"
                        },
                        new
                        {
                            Id = 27,
                            CountryName = "Bhutan"
                        },
                        new
                        {
                            Id = 28,
                            CountryName = "Bolivia"
                        },
                        new
                        {
                            Id = 29,
                            CountryName = "Bosnia & Herzegovina"
                        },
                        new
                        {
                            Id = 30,
                            CountryName = "Botswana"
                        },
                        new
                        {
                            Id = 31,
                            CountryName = "Bouvet Island"
                        },
                        new
                        {
                            Id = 32,
                            CountryName = "Brazil"
                        },
                        new
                        {
                            Id = 33,
                            CountryName = "British Indian Ocean Territory"
                        },
                        new
                        {
                            Id = 34,
                            CountryName = "British Virgin Islands"
                        },
                        new
                        {
                            Id = 35,
                            CountryName = "Brunei"
                        },
                        new
                        {
                            Id = 36,
                            CountryName = "Bulgaria"
                        },
                        new
                        {
                            Id = 37,
                            CountryName = "Burkina Faso"
                        },
                        new
                        {
                            Id = 38,
                            CountryName = "Burundi"
                        },
                        new
                        {
                            Id = 39,
                            CountryName = "Cambodia"
                        },
                        new
                        {
                            Id = 40,
                            CountryName = "Cameroon"
                        },
                        new
                        {
                            Id = 41,
                            CountryName = "Canada"
                        },
                        new
                        {
                            Id = 42,
                            CountryName = "Cape Verde"
                        },
                        new
                        {
                            Id = 43,
                            CountryName = "Caribbean Netherlands"
                        },
                        new
                        {
                            Id = 44,
                            CountryName = "Cayman Islands"
                        },
                        new
                        {
                            Id = 45,
                            CountryName = "Central African Republic"
                        },
                        new
                        {
                            Id = 46,
                            CountryName = "Chad"
                        },
                        new
                        {
                            Id = 47,
                            CountryName = "Chile"
                        },
                        new
                        {
                            Id = 48,
                            CountryName = "China"
                        },
                        new
                        {
                            Id = 49,
                            CountryName = "Christmas Island"
                        },
                        new
                        {
                            Id = 50,
                            CountryName = "Cocos(Keeling) Islands"
                        },
                        new
                        {
                            Id = 51,
                            CountryName = "Colombia"
                        },
                        new
                        {
                            Id = 52,
                            CountryName = "Comoros"
                        },
                        new
                        {
                            Id = 53,
                            CountryName = "Congo - Brazzaville"
                        },
                        new
                        {
                            Id = 54,
                            CountryName = "Congo - Kinshasa"
                        },
                        new
                        {
                            Id = 55,
                            CountryName = "Cook Islands"
                        },
                        new
                        {
                            Id = 56,
                            CountryName = "Costa Rica"
                        },
                        new
                        {
                            Id = 57,
                            CountryName = "Côte d’Ivoire"
                        },
                        new
                        {
                            Id = 58,
                            CountryName = "Croatia"
                        },
                        new
                        {
                            Id = 59,
                            CountryName = "Cuba"
                        },
                        new
                        {
                            Id = 60,
                            CountryName = "Curaçao"
                        },
                        new
                        {
                            Id = 61,
                            CountryName = "Cyprus"
                        },
                        new
                        {
                            Id = 62,
                            CountryName = "Czechia"
                        },
                        new
                        {
                            Id = 63,
                            CountryName = "Denmark"
                        },
                        new
                        {
                            Id = 64,
                            CountryName = "Djibouti"
                        },
                        new
                        {
                            Id = 65,
                            CountryName = "Dominica"
                        },
                        new
                        {
                            Id = 66,
                            CountryName = "Dominican Republic"
                        },
                        new
                        {
                            Id = 67,
                            CountryName = "Ecuador"
                        },
                        new
                        {
                            Id = 68,
                            CountryName = "Egypt"
                        },
                        new
                        {
                            Id = 69,
                            CountryName = "El Salvador"
                        },
                        new
                        {
                            Id = 70,
                            CountryName = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = 71,
                            CountryName = "Eritrea"
                        },
                        new
                        {
                            Id = 72,
                            CountryName = "Estonia"
                        },
                        new
                        {
                            Id = 73,
                            CountryName = "Eswatini"
                        },
                        new
                        {
                            Id = 74,
                            CountryName = "Ethiopia"
                        },
                        new
                        {
                            Id = 75,
                            CountryName = "Falkland Islands"
                        },
                        new
                        {
                            Id = 76,
                            CountryName = "Faroe Islands"
                        },
                        new
                        {
                            Id = 77,
                            CountryName = "Fiji"
                        },
                        new
                        {
                            Id = 78,
                            CountryName = "Finland"
                        },
                        new
                        {
                            Id = 79,
                            CountryName = "France"
                        },
                        new
                        {
                            Id = 80,
                            CountryName = "French Guiana"
                        },
                        new
                        {
                            Id = 81,
                            CountryName = "French Polynesia"
                        },
                        new
                        {
                            Id = 82,
                            CountryName = "French Southern Territories"
                        },
                        new
                        {
                            Id = 83,
                            CountryName = "Gabon"
                        },
                        new
                        {
                            Id = 84,
                            CountryName = "Gambia"
                        },
                        new
                        {
                            Id = 85,
                            CountryName = "Georgia"
                        },
                        new
                        {
                            Id = 86,
                            CountryName = "Germany"
                        },
                        new
                        {
                            Id = 87,
                            CountryName = "Ghana"
                        },
                        new
                        {
                            Id = 88,
                            CountryName = "Gibraltar"
                        },
                        new
                        {
                            Id = 89,
                            CountryName = "Greece"
                        },
                        new
                        {
                            Id = 90,
                            CountryName = "Greenland"
                        },
                        new
                        {
                            Id = 91,
                            CountryName = "Grenada"
                        },
                        new
                        {
                            Id = 92,
                            CountryName = "Guadeloupe"
                        },
                        new
                        {
                            Id = 93,
                            CountryName = "Guam"
                        },
                        new
                        {
                            Id = 94,
                            CountryName = "Guatemala"
                        },
                        new
                        {
                            Id = 95,
                            CountryName = "Guernsey"
                        },
                        new
                        {
                            Id = 96,
                            CountryName = "Guinea"
                        },
                        new
                        {
                            Id = 97,
                            CountryName = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = 98,
                            CountryName = "Guyana"
                        },
                        new
                        {
                            Id = 99,
                            CountryName = "Haiti"
                        },
                        new
                        {
                            Id = 100,
                            CountryName = "Heard & McDonald Islands"
                        },
                        new
                        {
                            Id = 101,
                            CountryName = "Honduras"
                        },
                        new
                        {
                            Id = 102,
                            CountryName = "Hong Kong SAR China"
                        },
                        new
                        {
                            Id = 103,
                            CountryName = "Hungary"
                        },
                        new
                        {
                            Id = 104,
                            CountryName = "Iceland"
                        },
                        new
                        {
                            Id = 105,
                            CountryName = "India"
                        },
                        new
                        {
                            Id = 106,
                            CountryName = "Indonesia"
                        },
                        new
                        {
                            Id = 107,
                            CountryName = "Iran"
                        },
                        new
                        {
                            Id = 108,
                            CountryName = "Iraq"
                        },
                        new
                        {
                            Id = 109,
                            CountryName = "Ireland"
                        },
                        new
                        {
                            Id = 110,
                            CountryName = "Isle of Man"
                        },
                        new
                        {
                            Id = 112,
                            CountryName = "Italy"
                        },
                        new
                        {
                            Id = 113,
                            CountryName = "Jamaica"
                        },
                        new
                        {
                            Id = 114,
                            CountryName = "Japan"
                        },
                        new
                        {
                            Id = 115,
                            CountryName = "Jersey"
                        },
                        new
                        {
                            Id = 116,
                            CountryName = "Jordan"
                        },
                        new
                        {
                            Id = 117,
                            CountryName = "Kazakhstan"
                        },
                        new
                        {
                            Id = 118,
                            CountryName = "Kenya"
                        },
                        new
                        {
                            Id = 119,
                            CountryName = "Kiribati"
                        },
                        new
                        {
                            Id = 120,
                            CountryName = "Kuwait"
                        },
                        new
                        {
                            Id = 121,
                            CountryName = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = 122,
                            CountryName = "Laos"
                        },
                        new
                        {
                            Id = 123,
                            CountryName = "Latvia"
                        },
                        new
                        {
                            Id = 124,
                            CountryName = "Lebanon"
                        },
                        new
                        {
                            Id = 125,
                            CountryName = "Lesotho"
                        },
                        new
                        {
                            Id = 126,
                            CountryName = "Liberia"
                        },
                        new
                        {
                            Id = 127,
                            CountryName = "Libya"
                        },
                        new
                        {
                            Id = 128,
                            CountryName = "Liechtenstein"
                        },
                        new
                        {
                            Id = 129,
                            CountryName = "Lithuania"
                        },
                        new
                        {
                            Id = 130,
                            CountryName = "Luxembourg"
                        },
                        new
                        {
                            Id = 131,
                            CountryName = "Macao SAR China"
                        },
                        new
                        {
                            Id = 132,
                            CountryName = "Madagascar"
                        },
                        new
                        {
                            Id = 133,
                            CountryName = "Malawi"
                        },
                        new
                        {
                            Id = 134,
                            CountryName = "Malaysia"
                        },
                        new
                        {
                            Id = 135,
                            CountryName = "Maldives"
                        },
                        new
                        {
                            Id = 136,
                            CountryName = "Mali"
                        },
                        new
                        {
                            Id = 137,
                            CountryName = "Malta"
                        },
                        new
                        {
                            Id = 138,
                            CountryName = "Marshall Islands"
                        },
                        new
                        {
                            Id = 139,
                            CountryName = "Martinique"
                        },
                        new
                        {
                            Id = 140,
                            CountryName = "Mauritania"
                        },
                        new
                        {
                            Id = 141,
                            CountryName = "Mauritius"
                        },
                        new
                        {
                            Id = 142,
                            CountryName = "Mayotte"
                        },
                        new
                        {
                            Id = 143,
                            CountryName = "Mexico"
                        },
                        new
                        {
                            Id = 144,
                            CountryName = "Micronesia"
                        },
                        new
                        {
                            Id = 145,
                            CountryName = "Moldova"
                        },
                        new
                        {
                            Id = 146,
                            CountryName = "Monaco"
                        },
                        new
                        {
                            Id = 147,
                            CountryName = "Mongolia"
                        },
                        new
                        {
                            Id = 148,
                            CountryName = "Montenegro"
                        },
                        new
                        {
                            Id = 149,
                            CountryName = "Montserrat"
                        },
                        new
                        {
                            Id = 150,
                            CountryName = "Morocco"
                        },
                        new
                        {
                            Id = 151,
                            CountryName = "Mozambique"
                        },
                        new
                        {
                            Id = 152,
                            CountryName = "Myanmar(Burma)"
                        },
                        new
                        {
                            Id = 153,
                            CountryName = "Namibia"
                        },
                        new
                        {
                            Id = 154,
                            CountryName = "Nauru"
                        },
                        new
                        {
                            Id = 155,
                            CountryName = "Nepal"
                        },
                        new
                        {
                            Id = 156,
                            CountryName = "Netherlands"
                        },
                        new
                        {
                            Id = 157,
                            CountryName = "New Caledonia"
                        },
                        new
                        {
                            Id = 158,
                            CountryName = "New Zealand"
                        },
                        new
                        {
                            Id = 159,
                            CountryName = "Nicaragua"
                        },
                        new
                        {
                            Id = 160,
                            CountryName = "Niger"
                        },
                        new
                        {
                            Id = 161,
                            CountryName = "Nigeria"
                        },
                        new
                        {
                            Id = 162,
                            CountryName = "Niue"
                        },
                        new
                        {
                            Id = 163,
                            CountryName = "Norfolk Island"
                        },
                        new
                        {
                            Id = 164,
                            CountryName = "North Korea"
                        },
                        new
                        {
                            Id = 165,
                            CountryName = "North Macedonia"
                        },
                        new
                        {
                            Id = 166,
                            CountryName = "Northern Mariana Islands"
                        },
                        new
                        {
                            Id = 167,
                            CountryName = "Norway"
                        },
                        new
                        {
                            Id = 168,
                            CountryName = "Oman"
                        },
                        new
                        {
                            Id = 169,
                            CountryName = "Pakistan"
                        },
                        new
                        {
                            Id = 170,
                            CountryName = "Palau"
                        },
                        new
                        {
                            Id = 171,
                            CountryName = "Palestinian Territories"
                        },
                        new
                        {
                            Id = 172,
                            CountryName = "Panama"
                        },
                        new
                        {
                            Id = 173,
                            CountryName = "Papua New Guinea"
                        },
                        new
                        {
                            Id = 174,
                            CountryName = "Paraguay"
                        },
                        new
                        {
                            Id = 175,
                            CountryName = "Peru"
                        },
                        new
                        {
                            Id = 176,
                            CountryName = "Philippines"
                        },
                        new
                        {
                            Id = 177,
                            CountryName = "Pitcairn Islands"
                        },
                        new
                        {
                            Id = 178,
                            CountryName = "Poland"
                        },
                        new
                        {
                            Id = 179,
                            CountryName = "Portugal"
                        },
                        new
                        {
                            Id = 180,
                            CountryName = "Puerto Rico"
                        },
                        new
                        {
                            Id = 181,
                            CountryName = "Qatar"
                        },
                        new
                        {
                            Id = 182,
                            CountryName = "Réunion"
                        },
                        new
                        {
                            Id = 183,
                            CountryName = "Romania"
                        },
                        new
                        {
                            Id = 184,
                            CountryName = "Russia"
                        },
                        new
                        {
                            Id = 185,
                            CountryName = "Rwanda"
                        },
                        new
                        {
                            Id = 186,
                            CountryName = "Samoa"
                        },
                        new
                        {
                            Id = 187,
                            CountryName = "San Marino"
                        },
                        new
                        {
                            Id = 188,
                            CountryName = "São Tomé & Príncipe"
                        },
                        new
                        {
                            Id = 189,
                            CountryName = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 190,
                            CountryName = "Senegal"
                        },
                        new
                        {
                            Id = 191,
                            CountryName = "Serbia"
                        },
                        new
                        {
                            Id = 192,
                            CountryName = "Seychelles"
                        },
                        new
                        {
                            Id = 193,
                            CountryName = "Sierra Leone"
                        },
                        new
                        {
                            Id = 194,
                            CountryName = "Singapore"
                        },
                        new
                        {
                            Id = 195,
                            CountryName = "Sint Maarten"
                        },
                        new
                        {
                            Id = 196,
                            CountryName = "Slovakia"
                        },
                        new
                        {
                            Id = 197,
                            CountryName = "Slovenia"
                        },
                        new
                        {
                            Id = 198,
                            CountryName = "Solomon Islands"
                        },
                        new
                        {
                            Id = 199,
                            CountryName = "Somalia"
                        },
                        new
                        {
                            Id = 200,
                            CountryName = "South Africa"
                        },
                        new
                        {
                            Id = 201,
                            CountryName = "South Georgia & South Sandwich Islands"
                        },
                        new
                        {
                            Id = 202,
                            CountryName = "South Korea"
                        },
                        new
                        {
                            Id = 203,
                            CountryName = "South Sudan"
                        },
                        new
                        {
                            Id = 204,
                            CountryName = "Spain"
                        },
                        new
                        {
                            Id = 205,
                            CountryName = "Sri Lanka"
                        },
                        new
                        {
                            Id = 206,
                            CountryName = "St.Barthélemy"
                        },
                        new
                        {
                            Id = 207,
                            CountryName = "St.Helena"
                        },
                        new
                        {
                            Id = 208,
                            CountryName = "St.Kitts & Nevis"
                        },
                        new
                        {
                            Id = 209,
                            CountryName = "St.Lucia"
                        },
                        new
                        {
                            Id = 210,
                            CountryName = "St.Martin"
                        },
                        new
                        {
                            Id = 211,
                            CountryName = "St.Pierre & Miquelon"
                        },
                        new
                        {
                            Id = 212,
                            CountryName = "St.Vincent & Grenadines"
                        },
                        new
                        {
                            Id = 213,
                            CountryName = "Sudan"
                        },
                        new
                        {
                            Id = 214,
                            CountryName = "Suriname"
                        },
                        new
                        {
                            Id = 215,
                            CountryName = "Svalbard & Jan Mayen"
                        },
                        new
                        {
                            Id = 216,
                            CountryName = "Sweden"
                        },
                        new
                        {
                            Id = 217,
                            CountryName = "Switzerland"
                        },
                        new
                        {
                            Id = 218,
                            CountryName = "Syria"
                        },
                        new
                        {
                            Id = 219,
                            CountryName = "Taiwan"
                        },
                        new
                        {
                            Id = 220,
                            CountryName = "Tajikistan"
                        },
                        new
                        {
                            Id = 221,
                            CountryName = "Tanzania"
                        },
                        new
                        {
                            Id = 222,
                            CountryName = "Thailand"
                        },
                        new
                        {
                            Id = 223,
                            CountryName = "Timor-Leste"
                        },
                        new
                        {
                            Id = 224,
                            CountryName = "Togo"
                        },
                        new
                        {
                            Id = 225,
                            CountryName = "Tokelau"
                        },
                        new
                        {
                            Id = 226,
                            CountryName = "Tonga"
                        },
                        new
                        {
                            Id = 227,
                            CountryName = "Trinidad & Tobago"
                        },
                        new
                        {
                            Id = 228,
                            CountryName = "Tunisia"
                        },
                        new
                        {
                            Id = 229,
                            CountryName = "Turkey"
                        },
                        new
                        {
                            Id = 230,
                            CountryName = "Turkmenistan"
                        },
                        new
                        {
                            Id = 231,
                            CountryName = "Turks & Caicos Islands"
                        },
                        new
                        {
                            Id = 232,
                            CountryName = "Tuvalu"
                        },
                        new
                        {
                            Id = 233,
                            CountryName = "U.S.Outlying Islands"
                        },
                        new
                        {
                            Id = 234,
                            CountryName = "U.S.Virgin Islands"
                        },
                        new
                        {
                            Id = 235,
                            CountryName = "Uganda"
                        },
                        new
                        {
                            Id = 236,
                            CountryName = "Ukraine"
                        },
                        new
                        {
                            Id = 237,
                            CountryName = "United Arab Emirates"
                        },
                        new
                        {
                            Id = 238,
                            CountryName = "United Kingdom"
                        },
                        new
                        {
                            Id = 239,
                            CountryName = "United States"
                        },
                        new
                        {
                            Id = 240,
                            CountryName = "Uruguay"
                        },
                        new
                        {
                            Id = 241,
                            CountryName = "Uzbekistan"
                        },
                        new
                        {
                            Id = 242,
                            CountryName = "Vanuatu"
                        },
                        new
                        {
                            Id = 243,
                            CountryName = "Vatican City"
                        },
                        new
                        {
                            Id = 244,
                            CountryName = "Venezuela"
                        },
                        new
                        {
                            Id = 245,
                            CountryName = "Vietnam"
                        },
                        new
                        {
                            Id = 246,
                            CountryName = "Wallis & Futuna"
                        },
                        new
                        {
                            Id = 247,
                            CountryName = "Western Sahara"
                        },
                        new
                        {
                            Id = 248,
                            CountryName = "Yemen"
                        },
                        new
                        {
                            Id = 249,
                            CountryName = "Zambia"
                        },
                        new
                        {
                            Id = 250,
                            CountryName = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("Journy.Model.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Journy.Model.features.Pin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PostsId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostsId");

                    b.HasIndex("UserId");

                    b.ToTable("Pins");
                });

            modelBuilder.Entity("Journy.Model.features.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageRating")
                        .HasColumnType("float");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("ImgPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Texts")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Journy.Model.features.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("UserAccountUserAccount", b =>
                {
                    b.Property<int>("FollowersId")
                        .HasColumnType("int");

                    b.Property<int>("FollowingId")
                        .HasColumnType("int");

                    b.HasKey("FollowersId", "FollowingId");

                    b.HasIndex("FollowingId");

                    b.ToTable("UserAccountUserAccount");
                });

            modelBuilder.Entity("Journy.Model.features.Pin", b =>
                {
                    b.HasOne("Journy.Model.features.Post", "Posts")
                        .WithMany()
                        .HasForeignKey("PostsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Journy.Model.UserAccount", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Posts");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Journy.Model.features.Post", b =>
                {
                    b.HasOne("Journy.Model.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Journy.Model.UserAccount", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserAccountUserAccount", b =>
                {
                    b.HasOne("Journy.Model.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("FollowersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Journy.Model.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("FollowingId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
